drop table if exists users cascade;
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL UNIQUE
);

drop table if exists requests cascade;
CREATE TABLE IF NOT EXISTS requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description VARCHAR(1024) NOT NULL,
  requestor_id BIGINT NOT NULL REFERENCES users(id) ON UPDATE cascade ON DELETE set null,
  created TIMESTAMP NOT NULL
);

drop table if exists items cascade;
CREATE TABLE IF NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(1024) NOT NULL,
  is_available BOOLEAN NOT NULL,
  owner_id BIGINT NOT NULL REFERENCES users(id) ON UPDATE cascade ON DELETE cascade,
  request_id BIGINT REFERENCES requests(id) ON UPDATE cascade ON DELETE set null
);

drop table if exists bookings cascade;
CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP NOT NULL,
  item_id BIGINT NOT NULL REFERENCES items(id) ON UPDATE cascade ON DELETE cascade,
  booker_id BIGINT NOT NULL REFERENCES users(id) ON UPDATE cascade ON DELETE cascade,
  status VARCHAR(10) NOT NULL
);

drop table if exists comments cascade;
CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text TEXT NOT NULL,
  item_id BIGINT NOT NULL REFERENCES items(id) ON UPDATE cascade ON DELETE cascade,
  author_id BIGINT NOT NULL REFERENCES users(id) ON UPDATE cascade ON DELETE cascade,
  created TIMESTAMP NOT NULL
);